# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'HBAlertControllerDemo'
project 'HBAlertControllerDemo.project'
project '../HBAlertControllerDemo/HBAlert/HBAlert.project'

target 'HBAlertControllerDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for HBAlertViewController
    pod 'Masonry'
    project 'HBAlertControllerDemo.project'
end

target 'HBAlert' do
    
    pod 'Masonry'
    project '../HBAlertControllerDemo/HBAlert/HBAlert.project'
end


